### ISSUE TITLE
Path isn't included in the frm-show-entry shortcode

### ISSUE THREAD

**Issue by stephywells** [Strategy11/formidable-user-tracking#9]
This also covers the email notifications. To see this, add a shortcode like this to a page:
[frm-show-entry id=28 user_info=1]

Entry created with 1.0:
<img width="769" alt="Screen Shot 2022-09-22 at 9 31 28 AM" src="https://user-images.githubusercontent.com/1116876/191789709-63946b83-e0e1-4281-a1da-22dd044c2a22.png">

Entry created with 2.0:
<img width="623" alt="Screen Shot 2022-09-22 at 9 31 37 AM" src="https://user-images.githubusercontent.com/1116876/191789695-e2a6b8d4-aa9a-44e7-b4d2-2f63b29036e9.png">

**Comment by AbdiTolesa** [comment]
@stephywells I'm not sure if you have noticed it but I think this issue isn't just limited to shortcodes but seems to happen when you view an entry as the url doesn't include the server path when it is created in v1.0. I would make sure the path is included for those the same version.

**Comment by stephywells** [comment]
@AbdiTolesa I'm not sure I'm understanding. The problem is that the user journey should show in the email and in the frm-show-entry shortcode when user_info=1 is included. This is a checkbox in the email settings.

We should use a hook in Lite to add the journey there. I'm not seeing a hook, so we might need to add one at the end of the FrmEntryValues::init_user_info() function. Then we can replace referrer in that array.

**Comment by AbdiTolesa** [comment]
@stephywells Thanks for clarifying this as I was misunderstanding it from the title when it says 'path'. Will do it accordingly.

**Comment by stephywells** [comment]
@AbdiTolesa This looks really sloppy. It needs to be redone.
<img width="758" alt="Screen Shot 2022-10-11 at 11 32 23 AM" src="https://user-images.githubusercontent.com/1116876/195160650-9760e9a4-9b34-4c88-b96e-99ae8ff533ab.png">

This HTML should only include <br/> since it needs to work for plan text emails too. It can't add a new set of styling nested inside of something else.

**Comment by stephywells** [comment]
This has been updated now:
<img width="703" alt="Screen Shot 2022-10-11 at 1 53 04 PM" src="https://user-images.githubusercontent.com/1116876/195185868-b34e7b16-579f-4d9c-a87e-cf3771faa221.png">

**Comment by AbdiTolesa** [comment]
> This has been updated now: <img alt="Screen Shot 2022-10-11 at 1 53 04 PM" width="703" src="https://user-images.githubusercontent.com/1116876/195185868-b34e7b16-579f-4d9c-a87e-cf3771faa221.png">

@stephywells I was working on this as well but you just get it done quicker. My update renders html conditionally though, meaning if the email is html it includes the link, middot etc pretty much as in the entry view page but shows just plain text without those for plain text. I reused most of the existing code from the `user_tracking.php`, extracting common logic to a new function.

**Comment by stephywells** [comment]
Thanks! I didn't realize you were working on this.

I'd love to see what you came up with in a new PR. It sounds like some of that would be good to merge.
